# Generated by Django 4.1.5 on 2023-04-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=20)),
                ('banner_brief', models.CharField(max_length=100)),
                ('banner_img', models.ImageField(upload_to='static/media')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'indexbanner',
            },
        ),
    ]
